```{r}
library(openxlsx)
library(dplyr)

# Adequação da Formação dos Docentes
# 2013
afd_2013 = read.xlsx("adequacao formacao docente_2013.xlsx")

afd_2013 = afd_2013 %>% select(1:4, "X6", "X9", 15:19)
afd_2013 = afd_2013[-c(1:8),]
colnames(afd_2013) = c("ano", "regiao", "uf", "municipio", "escola", "adm", "afd1", "afd2", "afd3", "afd4", "afd5")
for(i in 7:11){
  afd_2013[i] = as.numeric(unlist(afd_2013[i]))  
}
afd_2013 = afd_2013[afd_2013$adm == "Municipal",]
afd_2013 = afd_2013[, -c(6)]
write.csv(afd_2013, file = "csvlimpos/afd_2013.csv", row.names = FALSE)


# 2015
afd_2015 = read.xlsx("adequacao formacao docente_2015.xlsx")
afd_2015 = afd_2015[-c(1:8),-c(5, 7, 8, 10, 11:14, 20:44)]
colnames(afd_2015) = c("ano", "regiao", "uf", "municipio", "escola", "adm", "afd1", "afd2", "afd3", "afd4", "afd5")
for(i in 7:11){
  afd_2015[i] = as.numeric(unlist(afd_2015[i]))  
}
afd_2015 = afd_2015[afd_2015$adm == "Municipal",]
afd_2015 = afd_2015[, -c(6)]
write.csv(afd_2015, file = "csvlimpos/afd_2015.csv", row.names = FALSE)

# 2017
afd_2017 = read.xlsx("adequacao formacao docente_2017.xlsx")
afd_2017 = afd_2017[-c(1:8),-c(5, 7, 8, 10, 11:14, 20:44)]
colnames(afd_2017) = c("ano", "regiao", "uf", "municipio", "escola", "adm", "afd1", "afd2", "afd3", "afd4", "afd5")
for(i in 7:11){
  afd_2017[i] = as.numeric(unlist(afd_2017[i]))  
}
afd_2017 = afd_2017[afd_2017$adm == "Municipal",]
afd_2017 = afd_2017[, -c(6)]
write.csv(afd_2017, file = "csvlimpos/afd_2017.csv", row.names = FALSE)

# Média de Alunos por turma
# 2013
alunos_turma_2013 = read.xlsx("Media alunos turma_2013.xlsx")
alunos_turma_2013 = alunos_turma_2013[-c(1:8), -c(5, 7, 8, 10:12, 14:31)]
colnames(alunos_turma_2013) = c("ano", "regiao", "uf", "municipio", "escola", "adm", "media_aluno_turma")
alunos_turma_2013$media_aluno_turma = as.numeric(alunos_turma_2013$media_aluno_turma)
alunos_turma_2013 = alunos_turma_2013[alunos_turma_2013$adm == "Municipal",]
alunos_turma_2013 = alunos_turma_2013[, -c(6)]
write.csv(alunos_turma_2013, file = "csvlimpos/alunos_turma_2013.csv", row.names = FALSE)

# 2015
alunos_turma_2015 = read.xlsx("Media alunos turma_2015.xlsx")
alunos_turma_2015 = alunos_turma_2015[-c(1:8), -c(4, 6, 8, 10:12, 14:31)]
colnames(alunos_turma_2015) = c("ano", "regiao", "uf", "municipio", "escola", "adm", "media_aluno_turma")
alunos_turma_2015$media_aluno_turma = as.numeric(alunos_turma_2015$media_aluno_turma)
class(alunos_turma_2015$media_aluno_turma)
alunos_turma_2015 = alunos_turma_2015[alunos_turma_2015$adm == "Municipal",]
alunos_turma_2015 = alunos_turma_2015[, -c(6)]
write.csv(alunos_turma_2015, file = "csvlimpos/alunos_turma_2015.csv", row.names = FALSE)

# 2017
alunos_turma_2017 = read.xlsx("Media alunos turma_2017.xlsx")
alunos_turma_2017 = alunos_turma_2017[, -c(5, 7, 8, 10:12, 14:31)]
alunos_turma_2017 = alunos_turma_2017[-c(1:8),]
colnames(alunos_turma_2017) = c("ano", "regiao", "uf", "municipio", "escola", "adm", "media_aluno_turma")
alunos_turma_2017$media_aluno_turma = as.numeric(alunos_turma_2017$media_aluno_turma)
alunos_turma_2017 = alunos_turma_2017[alunos_turma_2017$adm == "Municipal",]
alunos_turma_2017 = alunos_turma_2017[, -c(6)]
write.csv(alunos_turma_2017, file = "csvlimpos/alunos_turma_2017.csv", row.names = FALSE)

# Percentual Docente com Curso Superior
# 2013
superior_2013 = read.xlsx("percentual docente curso superior_2013.xlsx")
superior_2013 = superior_2013[, -c(4, 5, 7, 10, 11:13, 15:20)]
superior_2013 = superior_2013[-c(1:7),]
colnames(superior_2013) = c("ano", "regiao", "uf", "municipio", "adm", "escola", "superior")
superior_2013$superior = as.numeric(superior_2013$superior)
superior_2013 = superior_2013[superior_2013$adm == "Municipal",]
superior_2013 = superior_2013[, -c(5)]

# 2015
superior_2015 = read.xlsx("percentual docente curso superior_2015.xlsx")
superior_2015 = superior_2015[, -c(4:5, 7, 9, 11:13, 15:20)]
superior_2015 = superior_2015[-c(1:7),]
colnames(superior_2015) = c("ano", "regiao", "uf", "municipio", "adm", "escola", "superior")
superior_2015$superior = as.numeric(superior_2015$superior)
superior_2015 = superior_2015[superior_2015$adm == "Municipal",]
superior_2015 = superior_2015[, -c(5)]

# 2017
superior_2017 = read.xlsx("percentual docente curso superior_2017.xlsx")
superior_2017 = superior_2017[, -c(5, 7:8, 10:12, 14:19)]
superior_2017 = superior_2017[-c(1:7),]
colnames(superior_2017) = c("ano", "regiao", "uf", "municipio", "escola", "adm", "superior")
superior_2017$superior = as.numeric(superior_2017$superior)
superior_2017 = superior_2017[superior_2017$adm == "Municipal",]
superior_2017 = superior_2017[, -c(6)]

write.csv(superior_2013, file = "csvlimpos/superior_2013.csv", row.names = FALSE)
write.csv(superior_2015, file = "csvlimpos/superior_2015.csv", row.names = FALSE)
write.csv(superior_2017, file = "csvlimpos/superior_2017.csv", row.names = FALSE)

# Regularidade Corpo Docente
# 2013
regularidade_2013 = read.xlsx("regularidade corpo docente_2013.xlsx")
regularidade_2013 = regularidade_2013[, -c(3, 5, 7:8)]
regularidade_2013 = regularidade_2013[-c(1:5),]
colnames(regularidade_2013) = c("ano", "regiao", "municipio", "escola", "adm", "MIRD")
regularidade_2013$MIRD = as.numeric(regularidade_2013$MIRD)
regularidade_2013 = regularidade_2013[regularidade_2013$adm == "Municipal",]
regularidade_2013 = regularidade_2013[, -c(5)]

# 2015
regularidade_2015 = read.xlsx("regularidade corpo docente_2015.xlsx")
regularidade_2015 = regularidade_2015[, -c(5, 7:8)]
regularidade_2015 = regularidade_2015[-c(1:5),]
colnames(regularidade_2015) = c("ano", "regiao", "uf", "municipio", "escola", "adm", "MIRD")
regularidade_2015$MIRD = as.numeric(regularidade_2015$MIRD)
regularidade_2015 = regularidade_2015[regularidade_2015$adm == "Municipal",]
regularidade_2015 = regularidade_2015[, -c(6)]

# 2017
regularidade_2017 = read.xlsx("regularidade corpo docente_2017.xlsx")
regularidade_2017 = regularidade_2017[, -c(5, 7:8)]
regularidade_2017 = regularidade_2017[-c(1:5),]
colnames(regularidade_2017) = c("ano", "regiao", "uf", "municipio", "escola", "adm", "MIRD")
regularidade_2017$MIRD = as.numeric(regularidade_2017$MIRD)
regularidade_2017 = regularidade_2017[regularidade_2017$adm == "Municipal",]
regularidade_2017 = regularidade_2017[, -c(6)]

write.csv(regularidade_2013, file = "csvlimpos/regularidade_2013.csv", row.names = FALSE)
write.csv(regularidade_2015, file = "csvlimpos/regularidade_2015.csv", row.names = FALSE)
write.csv(regularidade_2017, file = "csvlimpos/regularidade_2017.csv", row.names = FALSE)

# Remuneração docentes municípios
# 2014
remuneracao_2014 = read.xlsx("Remuneracao_docentes_Municipios_2014.xlsx")
remuneracao_2014 = remuneracao_2014[, -c(5, 7:11, 13:15)]
remuneracao_2014 = remuneracao_2014[-c(1:7),]
colnames(remuneracao_2014) = c("ano", "regiao", "uf", "municipio", "adm", "salario_medio", "salario_medio_pad")
for(i in 6:7){
  remuneracao_2014[i] = as.numeric(unlist(remuneracao_2014[i]))
}
remuneracao_2014 = remuneracao_2014[remuneracao_2014$adm == "Municipal",]
remuneracao_2014 = remuneracao_2014[, -c(5)]

# 2015
remuneracao_2015 = read.xlsx("Remuneracao_docentes_Municipios_2015.xlsx")
remuneracao_2015 = remuneracao_2015[, -c(5, 7:11, 13:15)]
remuneracao_2015 = remuneracao_2015[-c(1:7),]
colnames(remuneracao_2015) = c("ano", "regiao", "uf", "municipio", "adm", "salario_medio", "salario_medio_pad")
for(i in 6:7){
  remuneracao_2015[i] = as.numeric(unlist(remuneracao_2015[i]))
}
remuneracao_2015 = remuneracao_2015[remuneracao_2015$adm == "Municipal",]
remuneracao_2015 = remuneracao_2015[, -c(5)]

# 2017
remuneracao_2017 = read.xlsx("Remuneracao_docentes_Municipios_2017.xlsx")
remuneracao_2017 = remuneracao_2017[, -c(5, 7:11, 13:15)]
remuneracao_2017 = remuneracao_2017[-c(1:7),]
colnames(remuneracao_2017) = c("ano", "regiao", "uf", "municipio", "adm", "salario_medio", "salario_medio_pad")
for(i in 6:7){
  remuneracao_2017[i] = as.numeric(unlist(remuneracao_2017[i]))
}
remuneracao_2017 = remuneracao_2017[remuneracao_2017$adm == "Municipal",]
remuneracao_2017 = remuneracao_2017[, -c(5)]

write.csv(remuneracao_2014, file = "csvlimpos/remuneracao_2014.csv", row.names = FALSE)
write.csv(remuneracao_2015, file = "csvlimpos/remuneracao_2015.csv", row.names = FALSE)
write.csv(remuneracao_2017, file = "csvlimpos/remuneracao_2017.csv", row.names = FALSE)

# Taxa de Rendimento 
# 2013
rendimento_2013 = read.xlsx("taxa de rendimento_2013.xlsx")
rendimento_2013 = rendimento_2013[, -c(5:6, 8, 11:27, 29:45, 47:63)]
rendimento_2013 = rendimento_2013[-c(1:6), ]
colnames(rendimento_2013) = c("ano", "regiao", "uf", "municipio", "escola", "adm", "aprovacao", "reprovacao", "abandono")
for (i in 7:9){
  rendimento_2013[i] = as.numeric(unlist(rendimento_2013[i]))
}
rendimento_2013 = rendimento_2013[rendimento_2013$adm == "Municipal",]
rendimento_2013 = rendimento_2013[, -c(6)]

# 2015
rendimento_2015 = read.xlsx("taxa de rendimento_2015.xlsx")
rendimento_2015 = rendimento_2015[, -c(5, 7:8, 11:27, 29:45, 47:63)]
rendimento_2015 = rendimento_2015[-c(1:7), ]
colnames(rendimento_2015) = c("ano", "regiao", "uf", "municipio", "escola", "adm", "aprovacao", "reprovacao", "abandono")
for (i in 7:9){
  rendimento_2015[i] = as.numeric(unlist(rendimento_2015[i]))
}
rendimento_2015 = rendimento_2015[rendimento_2015$adm == "Municipal",]
rendimento_2015 = rendimento_2015[, -c(6)]

# 2017
rendimento_2017 = read.xlsx("taxa de rendimento_2017.xlsx")
rendimento_2017 = rendimento_2017[, -c(5, 7:8, 11:27, 29:45, 47:63)]
rendimento_2017 = rendimento_2017[-c(1:7), ]
colnames(rendimento_2017) = c("ano", "regiao", "uf", "municipio", "escola", "adm", "aprovacao", "reprovacao", "abandono")
for(i in 7:9){
  rendimento_2017[i] = as.numeric(unlist(rendimento_2017[i]))
}
rendimento_2017 = rendimento_2017[rendimento_2017$adm == "Municipal",]
rendimento_2017 = rendimento_2017[, -c(6)]

write.csv(rendimento_2013, file = "csvlimpos/rendimento_2013.csv", row.names = FALSE)
write.csv(rendimento_2015, file = "csvlimpos/rendimento_2015.csv", row.names = FALSE)
write.csv(rendimento_2017, file = "csvlimpos/rendimento_2017.csv", row.names = FALSE)

# nivel de complexidade da gestão
#2013
complexidade_2013 = read.xlsx("complexidade_2013.xlsx")
complexidade_2013 = complexidade_2013[-c(1:6), -c(5, 7)]
colnames(complexidade_2013) = c("ano", "regiao", "uf", "municipio", "adm", "gestao 1", "gestao 2",
                                "gestao 3", "gestao 4", "gestao 5", "gestao 6")
complexidade_2013 = complexidade_2013[complexidade_2013$adm == "Municipal",]
complexidade_2013 = complexidade_2013[, -c(5)]
for(i in 5:10){
    complexidade_2013[i] = as.numeric(unlist(complexidade_2013[i]))
}
write.csv(complexidade_2013, file = "csvlimpos/complexidade_2013.csv", row.names = FALSE)

#2015
complexidade_2015 = read.xlsx("complexidade_2015.xlsx")
complexidade_2015 = complexidade_2015[-c(1:6), -c(5, 7)]
colnames(complexidade_2015) = c("ano", "regiao", "uf", "municipio", "adm", "gestao 1", "gestao 2",
                                "gestao 3", "gestao 4", "gestao 5", "gestao 6")
complexidade_2015 = complexidade_2015[complexidade_2015$adm == "Municipal",]
complexidade_2015 = complexidade_2015[, -c(5)]
for(i in 5:10){
    complexidade_2015[i] = as.numeric(unlist(complexidade_2015[i]))
}
write.csv(complexidade_2015, file = "csvlimpos/complexidade_2015.csv", row.names = FALSE)

#2017
complexidade_2017 = read.xlsx("complexidade_2017.xlsx")
complexidade_2017 = complexidade_2017[-c(1:6), -c(5, 6)]
colnames(complexidade_2017) = c("ano", "regiao", "uf", "municipio", "adm", "gestao 1", "gestao 2",
                                "gestao 3", "gestao 4", "gestao 5", "gestao 6")
complexidade_2017 = complexidade_2017[complexidade_2017$adm == "Municipal",]
complexidade_2017 = complexidade_2017[, -c(5)]
for(i in 5:10){
    complexidade_2017[i] = as.numeric(unlist(complexidade_2017[i]))
}
write.csv(complexidade_2017, file = "csvlimpos/complexidade_2017.csv", row.names = FALSE)

```

```{r}
# agregação
# 2013
library(dplyr)
d2013 = inner_join(afd_2013, alunos_turma_2013, by = c("ano", "regiao", "uf", "municipio", "escola"))
d2013 = left_join(d2013, regularidade_2013, by = c("ano", "regiao", "municipio", "escola"))
d2013 = left_join(d2013, rendimento_2013, by = c("ano", "regiao", "uf", "municipio", "escola"))
d2013 = left_join(d2013, superior_2013, by = c("ano", "regiao", "uf", "municipio", "escola"))


# 2015
d2015 = inner_join(afd_2015, alunos_turma_2015, by = c("ano", "regiao", "uf", "municipio", "escola"))
d2015 = left_join(d2015, regularidade_2015, by = c("ano", "regiao", "uf", "municipio", "escola"))
d2015 = left_join(d2015, rendimento_2015, by = c("ano", "regiao", "uf", "municipio", "escola"))
d2015 = left_join(d2015, superior_2015, by = c("ano", "regiao", "uf", "municipio", "escola"))

# 2017
d2017 = inner_join(afd_2017, alunos_turma_2017, by = c("ano", "regiao", "uf", "municipio", "escola"))
d2017 = left_join(d2017, regularidade_2017, by = c("ano", "regiao", "uf", "municipio", "escola"))
d2017 = left_join(d2017, rendimento_2017, by = c("ano", "regiao", "uf", "municipio", "escola"))
d2017 = left_join(d2017, superior_2017, by = c("ano", "regiao", "uf", "municipio", "escola"))

```

```{r}
# Agregação por municipios ####
# 2013
mun_2013 = d2013
mun_2013 = mun_2013[,-c(5)]
mun_2013 = mun_2013 %>% group_by(ano, regiao, uf, municipio) %>% summarise_all(funs(mean(., na.rm = TRUE)))

# 2015
mun_2015 = d2015
mun_2015 = mun_2015[,-c(5)]
mun_2015 = mun_2015 %>% group_by(ano, regiao, uf, municipio) %>% summarise_all(funs(mean(., na.rm = TRUE)))

# 2017
mun_2017 = d2017
mun_2017 = mun_2017[,-c(5)]
mun_2017 = mun_2017 %>% group_by(ano, regiao, uf, municipio) %>% summarise_all(funs(mean(., na.rm = TRUE)))

```

```{r}
# remuneração 
remuneracao_2014 = remuneracao_2014[, -c(1:3)]
remuneracao_2014 = remuneracao_2014 %>% group_by(municipio) %>% summarise_all(funs(mean(., na.rm = TRUE)))
remuneracao_2015 = remuneracao_2015 %>% group_by(ano, regiao, uf, municipio) %>% summarise_all(funs(mean(., na.rm = TRUE)))
remuneracao_2017 = remuneracao_2017 %>% group_by(ano, regiao, uf, municipio) %>% summarise_all(funs(mean(., na.rm = TRUE)))
mun_2013 = left_join(mun_2013, remuneracao_2014, by = "municipio")
mun_2015 = left_join(mun_2015, remuneracao_2015, by = c("ano", "regiao", "uf", "municipio"))
mun_2017 = left_join(mun_2017, remuneracao_2017, by = c("ano", "regiao", "uf", "municipio"))

# complexidade
complexidade_2013 = complexidade_2013 %>% group_by(ano, regiao, uf, municipio) %>% summarise_all(funs(mean(., na.rm = TRUE)))
complexidade_2015 = complexidade_2015 %>% group_by(ano, regiao, uf, municipio) %>% summarise_all(funs(mean(., na.rm = TRUE)))
complexidade_2017 = complexidade_2017 %>% group_by(ano, regiao, uf, municipio) %>% summarise_all(funs(mean(., na.rm = TRUE)))
mun_2013 = left_join(mun_2013, complexidade_2013, by = c("ano", "regiao", "uf", "municipio"))
mun_2015 = left_join(mun_2015, complexidade_2015, by = c("ano", "regiao", "uf", "municipio"))
mun_2017 = left_join(mun_2017, complexidade_2017, by = c("ano", "regiao", "uf", "municipio"))

```

```{r}
# agregação final
dados_escolas = rbind(mun_2013, mun_2015, mun_2017)
write.csv(dados_escolas, file = "dados_escolas.csv", row.names = FALSE)
```
